check if has clang

diff --git a/.github/workflows/compile.yml b/.github/workflows/compile.yml
--- a/.github/workflows/compile.yml
+++ b/.github/workflows/compile.yml
@@ -11,10 +11,15 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Install Clang
+      - name: Check clang-format version
+        run: clang-format --version || echo "clang-format not found"
+
+      - name: Install Clang (if needed)
         run: |
-          sudo apt update
-          sudo apt install clang-format
+          if ! command -v clang-format &> /dev/null; then
+            sudo apt update
+            sudo apt install clang-format
+          fi
 
       - name: clang-format check
         run: make format-check
